[upstreams]
    [upstreams.backend]
    balancer="round_robin"
    provider="static"

        [[upstreams.backend.servers]]
            path="api.foo1.bar"
            weight=5    
        [[upstreams.backend.servers]]
            path="google.com"

    [upstreams.front]
        provider="static"
        balancer="round_robin"

        [[upstreams.front.servers]]
            path="http://api.bar1.baz"
            weight=5    

[server]
port=8081
    [[server.locations]]
        path="api/.+[/]"
        http_pass="backend"
    [[server.locations]]
        path="static/.+[/]"
        http_pass="front"
