[upstreams]
    [upstreams.backend]
        [[upstreams.backend.servers]]
            path="http://api.foo1.com"
            weight=5    
        [[upstreams.backend.servers]]
            path="http://api.foo2.com"

    [upstreams.front]
        provider="static"
        balancer="round_robin"

        [[upstreams.front.servers]]
            path="http://api.foo.com"
            weight=5    

[server]
    [[server.locations]]
        location="/api"
        upstream="backend"
    [[server.locations]]
        location="/"
        upstream="front"
