[upstreams]
    [upstreams.backend]
    balancer="round_robin"
    provider="static"

        [[upstreams.backend.servers]]
            path="http://api.foo1.com"
            weight=5    
        [[upstreams.backend.servers]]
            path="http://api.foo2.com"

    [upstreams.front]
        balancer="round_robin"

[server]
port=80
    [[server.locations]]
        path="/api"
        http_pass="backend"
    [[server.locations]]
        path="/"
        http_pass="front"
